docs: prepare for 0.3.0 and redesign website
kimlimjustin/xplorer pull request #205
Opened 2021-12-26 12:57 UTC by kimlimjustin

## Changes

* add extensions docs
* update locales
* redesign website

## Additional Comments

@stanleyowen @im-coder-lg could you please review this new website?

2021-12-26 13:08 UTC, stanleyowen requested changes
Love it! It would be great if you could add the sponsor and or subscribe to newsletter section(s). I greatly appreciate it!

2021-12-27 03:04 UTC, im-coder-lg commented
Oh sorry for the late reply, this happened 14 hours ago and GitHub Mobile didn't seem to inform me that I was mentioned here... Reviewing this soon!

2021-12-27 03:06 UTC, im-coder-lg commented
I say this is ready for merge, but I notice grammatical errors. I will make a new PR and fix that.

2021-12-28 12:47 UTC, stanleyowen approved these changes

2021-12-28 12:57 UTC, merged